// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGro_8H-C1z2rrylt20uZJBGXgiqNV-DM',
    appId: '1:298926772284:web:1b7c133e68cd124cbdb339',
    messagingSenderId: '298926772284',
    projectId: 'myntra-hackathon-a9c86',
    authDomain: 'myntra-hackathon-a9c86.firebaseapp.com',
    storageBucket: 'myntra-hackathon-a9c86.appspot.com',
    measurementId: 'G-NQ89RMPGFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwPYkOlagKQyY79zIVUD_YLfb38d_zR0',
    appId: '1:298926772284:android:f5b72db12ae96223bdb339',
    messagingSenderId: '298926772284',
    projectId: 'myntra-hackathon-a9c86',
    storageBucket: 'myntra-hackathon-a9c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQU9A-8fSQdhAVX9OgirMJ57rtqf81Es',
    appId: '1:298926772284:ios:476039c1d1aaededbdb339',
    messagingSenderId: '298926772284',
    projectId: 'myntra-hackathon-a9c86',
    storageBucket: 'myntra-hackathon-a9c86.appspot.com',
    iosBundleId: 'com.example.myntraCodestorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQU9A-8fSQdhAVX9OgirMJ57rtqf81Es',
    appId: '1:298926772284:ios:476039c1d1aaededbdb339',
    messagingSenderId: '298926772284',
    projectId: 'myntra-hackathon-a9c86',
    storageBucket: 'myntra-hackathon-a9c86.appspot.com',
    iosBundleId: 'com.example.myntraCodestorm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGro_8H-C1z2rrylt20uZJBGXgiqNV-DM',
    appId: '1:298926772284:web:6789f7627f5a0d6dbdb339',
    messagingSenderId: '298926772284',
    projectId: 'myntra-hackathon-a9c86',
    authDomain: 'myntra-hackathon-a9c86.firebaseapp.com',
    storageBucket: 'myntra-hackathon-a9c86.appspot.com',
    measurementId: 'G-TZX26345KP',
  );
}
